nodeLinker: node-modules
npmScopes:
  coin98-com:
    npmPublishRegistry: "https://packages.coin98.services/"
    npmRegistryServer: "https://packages.coin98.services/"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
